package(default_visibility = ["//visibility:public"])
alias(
    name = "studio-sdk",
    actual = "@android_studio//:studio-sdk",
)

alias(
    name = "studio-sdk-lib",
    actual = "@android_studio//:studio-sdk-lib",
)

alias(
    name = "studio-sdk-plugin-Groovy",
    actual = "@android_studio//:studio-sdk-plugin-Groovy",
)

alias(
    name = "studio-sdk-plugin-Groovy-lib",
    actual = "@android_studio//:studio-sdk-plugin-Groovy-lib",
)

alias(
    name = "studio-sdk-plugin-Kotlin",
    actual = "@android_studio//:studio-sdk-plugin-Kotlin",
)

alias(
    name = "studio-sdk-plugin-Kotlin-lib",
    actual = "@android_studio//:studio-sdk-plugin-Kotlin-lib",
)

alias(
    name = "studio-sdk-plugin-toml",
    actual = "@android_studio//:studio-sdk-plugin-toml",
)

alias(
    name = "studio-sdk-plugin-toml-lib",
    actual = "@android_studio//:studio-sdk-plugin-toml-lib",
)

alias(
    name = "studio-sdk-plugin-git4idea",
    actual = "@android_studio//:studio-sdk-plugin-git4idea",
)

alias(
    name = "studio-sdk-plugin-git4idea-lib",
    actual = "@android_studio//:studio-sdk-plugin-git4idea-lib",
)

alias(
    name = "studio-sdk-plugin-webp",
    actual = "@android_studio//:studio-sdk-plugin-webp",
)

alias(
    name = "studio-sdk-plugin-webp-lib",
    actual = "@android_studio//:studio-sdk-plugin-webp-lib",
)

alias(
    name = "studio-sdk-plugin-junit",
    actual = "@android_studio//:studio-sdk-plugin-junit",
)

alias(
    name = "studio-sdk-plugin-junit-lib",
    actual = "@android_studio//:studio-sdk-plugin-junit-lib",
)

alias(
    name = "studio-sdk-plugin-properties",
    actual = "@android_studio//:studio-sdk-plugin-properties",
)

alias(
    name = "studio-sdk-plugin-properties-lib",
    actual = "@android_studio//:studio-sdk-plugin-properties-lib",
)

alias(
    name = "studio-sdk-plugin-gradle",
    actual = "@android_studio//:studio-sdk-plugin-gradle",
)

alias(
    name = "studio-sdk-plugin-gradle-lib",
    actual = "@android_studio//:studio-sdk-plugin-gradle-lib",
)

alias(
    name = "studio-sdk-plugin-gradle-java",
    actual = "@android_studio//:studio-sdk-plugin-gradle-java",
)

alias(
    name = "studio-sdk-plugin-gradle-java-lib",
    actual = "@android_studio//:studio-sdk-plugin-gradle-java-lib",
)

alias(
    name = "studio-sdk-plugin-platform-images",
    actual = "@android_studio//:studio-sdk-plugin-platform-images",
)

alias(
    name = "studio-sdk-plugin-platform-images-lib",
    actual = "@android_studio//:studio-sdk-plugin-platform-images-lib",
)

alias(
    name = "studio-sdk-plugin-IntelliLang",
    actual = "@android_studio//:studio-sdk-plugin-IntelliLang",
)

alias(
    name = "studio-sdk-plugin-IntelliLang-lib",
    actual = "@android_studio//:studio-sdk-plugin-IntelliLang-lib",
)
